### ISSUE TITLE
Incompatability issues with portaudio19-dev / Make a snap or flatpak install?

### ISSUE THREAD

**Issue by m00-git** [sumanthratna/soundcloud9000#8]
When trying to install portaudio19-dev:

`The following additional packages will be installed:
  libasound2-dev libjack-dev libjack0 libportaudiocpp0
Suggested packages:
  libasound2-doc jackd1 portaudio19-doc
The following packages will be REMOVED:
  libasound2-plugins:i386 libjack-jackd2-0 libjack-jackd2-0:i386 regripper shellter sqldict wine-staging
  wine-staging-i386:i386 winehq-staging
The following NEW packages will be installed:
  libasound2-dev libjack-dev libjack0 libportaudiocpp0 portaudio19-dev
0 upgraded, 5 newly installed, 9 to remove and 0 not upgraded.
Need to get 583 kB of archives.
After this operation, 435 MB disk space will be freed.
Do you want to continue? [Y/n] 
`
all other dependencies are able to be installed without any problem, dont want to choose soundcloud9000 over wine-staging as wine-staging is necessary on my system. 

Ive had previous dependency issues resolved by using alternative snap/flatpak/or appimages
is it possible one of these can be made for soundcloud9000? Thank you.

**Comment by sumanthratna** [comment]
Thanks for opening this issue. I don't think the situation you're in is unique to soundcloud9000. 

That said, I will try to create a snap but you'll have to test it out and let me know if it works. If this doesn't work out, your best bet is to use [rbenv](https://github.com/rbenv/rbenv).

**Comment by sumanthratna** [comment]
@m00-git Can you try `snap install soundcloud9000` (or `sudo snap install soundcloud9000`) and let me know if the installation works for you?

**Comment by m00-git** [comment]
`sudo snap install soundcloud9000
error: cannot perform the following tasks:
- Mount snap "soundcloud9000" (1) (snap is unusable due to missing files; contact developer)
`

I appreciate the effort in helping me with my little dependency issue

**Comment by m00-git** [comment]
After installing all required dependencies I was able to install soundcloud9000 with gem (although when trying to launch I get load error. 

Snap package still wont install.

Im using Debian Sid. As I really do want to use this program (I love ncurses programs like this) im going to spool up a VM and try to see under what conditions I CAN get this to work.

**Comment by sumanthratna** [comment]
Status update: I *think* I've figured out the missing files issue. I'm also going to try including portaudio as a build-package so it can be included in the snap container. It should be published within the next hour.

**Comment by sumanthratna** [comment]
@m00-git Can you try the snap install again? 

If that doesn't work you might want to try running it in its own docker container.

**Comment by m00-git** [comment]
`sudo snap install soundcloud9000
error: cannot perform the following tasks:
- Mount snap "soundcloud9000" (2) (snap is unusable due to missing files; contact developer)
`
Will attempt with docker

**Comment by m00-git** [comment]
Couldnt really figure out Docker as I never used it before, and I dont care _that_ much about this program to get it to work under that.
I tried installing under a clean debian virtual machine and after installing the dependenices
`sudo apt install portaudio19-dev libmpg123-dev libncurses-dev ruby-dev`
and then `sudo gem install soundcloud9000`
and received the following
`Building native extensions. This could take a while...
ERROR:  Error installing soundcloud9000:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/json-1.8.6/ext/json/ext/generator
/usr/bin/ruby2.5 -r ./siteconf20200630-901-19wufhv.rb extconf.rb
creating Makefile

current directory: /var/lib/gems/2.5.0/gems/json-1.8.6/ext/json/ext/generator
make "DESTDIR=" clean
sh: 1: make: not found

current directory: /var/lib/gems/2.5.0/gems/json-1.8.6/ext/json/ext/generator
make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /var/lib/gems/2.5.0/gems/json-1.8.6 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/json-1.8.6/gem_make.out`

ended up going with tizonia instead for terminal soundcloud needs, although it lacks the ncurses interace

**Comment by sumanthratna** [comment]
re: snapcraft

Can you try to rerun the snapcraft install?

---
re: Docker

As opposed to a clean debian machine you might want to try a ruby container. See https://hub.docker.com/_/ruby. If you really don't want to spend more time on this, I understand :) Please let me know if you ever figure this out! Closing for now since you've decided on tizonia but if you want to pursue this then I'll reopen.
